/**
 * @file color.hxx
 * @brief Defines utilities for managing terminal colors in the Zylo programming language.
 *
 * This file contains the declaration of color-related utilities, responsible for managing
 * and applying colors to terminal output within the Zylo programming language. These utilities
 * enable the customization of text colors in the terminal, enhancing the readability and
 * visual appeal of output generated by Zylo programs. The file provides definitions for
 * various color codes and methods to apply these colors to strings before printing them
 * to the terminal.
 */

#ifndef ZYLO_UTILITIES_COLOR_HXX // ZYLO_UTILITIES_COLOR_HXX

#define ZYLO_UTILITIES_COLOR_HXX

#include <windows.h>

// Color Definitions

/**
 * @def RED
 * @brief Macro defining the color red for terminal output.
 *
 * Combines `FOREGROUND_RED` with `FOREGROUND_INTENSITY` to create a bright red color for text
 * in the terminal.
 */
#define RED (FOREGROUND_RED | FOREGROUND_INTENSITY)

/**
 * @def GREEN
 * @brief Macro defining the color green for terminal output.
 *
 * Combines `FOREGROUND_GREEN` with `FOREGROUND_INTENSITY` to create a bright green color for text
 * in the terminal.
 */
#define GREEN (FOREGROUND_GREEN | FOREGROUND_INTENSITY)

/**
 * @def BLUE
 * @brief Macro defining the color blue for terminal output.
 *
 * Combines `FOREGROUND_BLUE` with `FOREGROUND_INTENSITY` to create a bright blue color for text
 * in the terminal.
 */
#define BLUE (FOREGROUND_BLUE | FOREGROUND_INTENSITY)

/**
 * @def YELLOW
 * @brief Macro defining the color yellow for terminal output.
 *
 * Combines `FOREGROUND_RED`, `FOREGROUND_GREEN`, and `FOREGROUND_INTENSITY` to create a bright yellow
 * color for text in the terminal.
 */
#define YELLOW (FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY)

/**
 * @def CYAN
 * @brief Macro defining the color cyan for terminal output.
 *
 * Combines `FOREGROUND_GREEN`, `FOREGROUND_BLUE`, and `FOREGROUND_INTENSITY` to create a bright cyan
 * color for text in the terminal.
 */
#define CYAN (FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY)

/**
 * @def MAGENTA
 * @brief Macro defining the color magenta for terminal output.
 *
 * Combines `FOREGROUND_RED`, `FOREGROUND_BLUE`, and `FOREGROUND_INTENSITY` to create a bright magenta
 * color for text in the terminal.
 */
#define MAGENTA (FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_INTENSITY)

/**
 * @def WHITE
 * @brief Macro defining the color white for terminal output.
 *
 * Combines `FOREGROUND_RED`, `FOREGROUND_GREEN`, `FOREGROUND_BLUE`, and `FOREGROUND_INTENSITY` to create
 * a bright white color for text in the terminal.
 */
#define WHITE (FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY)

/**
 * @brief Sets the console text color in the terminal.
 *
 * This function applies the specified color to the terminal output by setting the console text
 * attribute. It uses the provided color code, which is typically one of the predefined color macros
 * like `RED`, `GREEN`, `BLUE`, etc. The function retrieves the console handle using `GetStdHandle`
 * and sets the text attribute using `SetConsoleTextAttribute`.
 *
 * @param color The color code to apply to the console text, typically a combination of foreground colors
 * and intensity flags.
 * @return Returns 0 on successful color change.
 *
 * @note This function is platform-dependent and is designed to work on Windows consoles. It may not be
 * portable to other operating systems.
 */
int SetConsoleColor(WORD color)
{
    HANDLE hConsole = GetStdHandle(STD_OUTPUT_HANDLE);
    SetConsoleTextAttribute(hConsole, color);
    return 0;
}

#endif // ZYLO_UTILITIES_COLOR_HXX